# .github/workflows/ci.yml
name: Application CI

on:
  push:
    branches:
      - main # Runs on pushes to main
      - '*'  # Runs on pushes to any branch (excluding main if main is also in pull_request)
             # To avoid double runs, more specific branch patterns or path filters might be needed later.
             # For now, this is okay for initial setup.
  pull_request:
    branches:
      - main # Runs on PRs targeting main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js for Frontend Linting
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
              # Changed cache-dependency-path to a glob pattern
              cache-dependency-path: '**/package-lock.json'

      - name: Install Frontend Dependencies & Lint
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint # Assumes 'lint' script is "next lint" or similar

      - name: Setup Python for Backend Linting
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Using Python 3.11 for CI as a stable recent version.
                                 # User is on 3.13 locally, this should be compatible for linting.

      - name: Install Backend Dev Dependencies & Lint
        working-directory: ./backend
        run: |
          pip install -r requirements-dev.txt # Contains flake8, black
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics # Basic flake8 check
          black . --check # Check formatting with black
