# .github/workflows/ci.yml
name: Application CI

on:
  push:
    branches:
      - main # Runs on pushes to main
      - '*'  # Runs on pushes to any branch (excluding main if main is also in pull_request)
             # To avoid double runs, more specific branch patterns or path filters might be needed later.
             # For now, this is okay for initial setup.
  pull_request:
    branches:
      - main # Runs on PRs targeting main

jobs:
  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
     
      - name: Install Frontend Dependencies & Run Tests
        working-directory: ./frontend
        run: |
          npm cache clean --force
          rm -rf node_modules
          npm ci
          npm test

  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      LANGCHAIN_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
      LANGCHAIN_TRACING_V2: "true"
      LANGCHAIN_PROJECT: "chatterbox-backend-tests"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
     
      - name: Install Backend Dependencies & Run Tests
        working-directory: ./backend
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          pytest tests/integration --cov=app --cov-report=xml

  e2e-tests:
    name: End-to-End Tests (Playwright)
    runs-on: ubuntu-latest
    needs: [frontend-tests, backend-tests]
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python for Playwright
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Playwright & Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libasound2t64 # Explicitly install the likely replacement
          pip install -r backend/requirements.txt -r backend/requirements-dev.txt
          playwright install --with-deps chromium

      - name: Run Playwright Tests
        working-directory: ./backend
        env:
          PLAYWRIGHT_BASE_URL: ${{ secrets.VERCEL_PREVIEW_URL || 'http://localhost:3000' }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGCHAIN_PROJECT: "chatterbox-e2e-tests"
          LANGCHAIN_TRACING_V2: "true"
        run: |
          pytest tests/e2e
